# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JDBaseModuleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JDBaseModuleDemo
  pod 'JDBaseModule', :path => "../../JDBaseModule"

  target 'JDBaseModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JDBaseModuleDemoUITests' do
    # Pods for testing
  end

end
